### ISSUE TITLE
Unable to open 2D t-series images

### ISSUE THREAD

**Issue by biophyschem** [macronucleus/chromagnon#17]
Hi,
I'm trying to import 2D t-series tif images with two colors as 16-bit composite files, but no files were appeared on the list. As an example, Chromagnon can import images with 20 slices of c=2, t=1, z=10 but cannot open those with 20 slices of c=2, t=10, z=1. 
How can I open the former ones? Thanks.

**Comment by macronucleus** [comment]
It is likely that Chromagnon cannot read your file format, since a 2D t-series tif image worked fine for me. Are you be willing to share your tif file with me? I will put a link to upload your file here tomorrow. Thanks.

**Comment by macronucleus** [comment]
I am sorry, it will be on the next Monday to put a link here. I could not connect to our server remotely today.

**Comment by biophyschem** [comment]
That's just fine with me. Thanks!

**Comment by macronucleus** [comment]
Here is the link to upload your tif file.
https://fexcc.nict.go.jp/user/~tg/gnt7n9oaajd47ig8rg53s72oc4
password: vq6Y57kkr4

By the way, are you using source installation of Chromagnon (v 6.9)?
If so, then the inability to read the time series is due to a different reason (I have mistakenly disabled to input image files with a single wavelength; I have fixed in my computer but not on GitHub yet).

**Comment by biophyschem** [comment]
I failed to log in to the system since log-in ID as well as password must be filled in the log-in window. So I have uploaded a sample image file here. I acquired the image with two different cameras, and made the composite file with Fiji.
I installed the Windows edition of the software on GitHub (Chromagnon065Win.zip). 

[TestImage.zip](https://github.com/macronucleus/Chromagnon/files/2923958/TestImage.zip)

**Comment by macronucleus** [comment]
I am sorry for putting a wrong link, and thank you for uploading your file in a public place.
I have located the problem in my code and already fixed in my computer.
I will make sure everything works before releasing the next version, since I have also made a lot of changes in the next release.
I believe you can use the new version by the end of the next week.
Please be patient.

**Comment by biophyschem** [comment]
Thanks a lot! I'm looking forward to the revision.

**Comment by macronucleus** [comment]
Hi, I have uploaded the new version v0.70.
Please check the "release" tab.
I believe the problem reading your tif file should be fixed.

By the way, with this version, you can choose wether to align the time axis or channels for a "multicolor timeseries image" from `extra parameters` dialog when you input such a file in the reference list.

**Comment by biophyschem** [comment]
Hi. This version works fine! Thank you very much for the quick response.
