### ISSUE TITLE
vendorised version of Priithon and Pricommon clash with existing packages

### ISSUE THREAD

**Issue by carandraug** [macronucleus/chromagnon#4]
Installing chromagnon from source will also install the vendorised versions of Priithon and Pricommon.  It would be nicer to have this as subpackages of chromagnon so they don't clash with existing installations. Alternatively, they could be not vendorised and handled as normal dependencies like bioformats, fftw, etc.

**Comment by macronucleus** [comment]
I have reorganized the folders so that they don't crush anymore.

Please note that the folder name of the newer version (>0.56) of Chromagnon is capitalized ('Chromagnon') while older version (<0.55) is not ('chromagnon').
Please uninstall the older 'chromagnon' (and priithon/pricommon) before installing the newer version, since they are recognized as different program by python.
