### ISSUE TITLE
Command line execution

### ISSUE THREAD

**Issue by juliomateoslangerak** [macronucleus/chromagnon#6]
HI,
Not really an issue but... Is it possible to run Chromagnon from the command line?
If yes, could you provide a quick reference of how to do it?
Thanks.
BTW: Chromagnon rocks!

**Comment by macronucleus** [comment]
Hi, thanks a lot for the feedback.
I fixed the code (v0.61) so that you can run Chromagnon from the command line if you install it from the source.
On linux,
$ chromagnon -h
will show you the help (see the Document page 10 for platform dependent call for the program).
The options are very similar to the graphical interface.
You need a single reference file (-R option), and can have multiple target files.
I hope it works for you.
Atsushi
